//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kudvenkat.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumOperationBi", Namespace="http://tempuri.org/WebServiceCalculator")]
    public enum EnumOperationBi : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sub = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mul = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Div = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/WebServiceCalculator", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WebServiceCalculator", ConfigurationName="CalculatorService.WebServiceCalculatorSoap")]
    public interface WebServiceCalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/ExecuteOperation", ReplyAction="*")]
        float ExecuteOperation(float firstNumber, float secondNumber, kudvenkat.CalculatorService.EnumOperationBi operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/ExecuteOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<float> ExecuteOperationAsync(float firstNumber, float secondNumber, kudvenkat.CalculatorService.EnumOperationBi operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/Add", ReplyAction="*")]
        int Add(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber);
        
        // CODEGEN: Generating message contract since element name GetLogOperationsResult from namespace http://tempuri.org/WebServiceCalculator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/GetLogOperations", ReplyAction="*")]
        kudvenkat.CalculatorService.GetLogOperationsResponse GetLogOperations(kudvenkat.CalculatorService.GetLogOperationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceCalculator/GetLogOperations", ReplyAction="*")]
        System.Threading.Tasks.Task<kudvenkat.CalculatorService.GetLogOperationsResponse> GetLogOperationsAsync(kudvenkat.CalculatorService.GetLogOperationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogOperationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogOperations", Namespace="http://tempuri.org/WebServiceCalculator", Order=0)]
        public kudvenkat.CalculatorService.GetLogOperationsRequestBody Body;
        
        public GetLogOperationsRequest() {
        }
        
        public GetLogOperationsRequest(kudvenkat.CalculatorService.GetLogOperationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLogOperationsRequestBody {
        
        public GetLogOperationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogOperationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogOperationsResponse", Namespace="http://tempuri.org/WebServiceCalculator", Order=0)]
        public kudvenkat.CalculatorService.GetLogOperationsResponseBody Body;
        
        public GetLogOperationsResponse() {
        }
        
        public GetLogOperationsResponse(kudvenkat.CalculatorService.GetLogOperationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServiceCalculator")]
    public partial class GetLogOperationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public kudvenkat.CalculatorService.ArrayOfString GetLogOperationsResult;
        
        public GetLogOperationsResponseBody() {
        }
        
        public GetLogOperationsResponseBody(kudvenkat.CalculatorService.ArrayOfString GetLogOperationsResult) {
            this.GetLogOperationsResult = GetLogOperationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculatorSoapChannel : kudvenkat.CalculatorService.WebServiceCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculatorSoapClient : System.ServiceModel.ClientBase<kudvenkat.CalculatorService.WebServiceCalculatorSoap>, kudvenkat.CalculatorService.WebServiceCalculatorSoap {
        
        public WebServiceCalculatorSoapClient() {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float ExecuteOperation(float firstNumber, float secondNumber, kudvenkat.CalculatorService.EnumOperationBi operation) {
            return base.Channel.ExecuteOperation(firstNumber, secondNumber, operation);
        }
        
        public System.Threading.Tasks.Task<float> ExecuteOperationAsync(float firstNumber, float secondNumber, kudvenkat.CalculatorService.EnumOperationBi operation) {
            return base.Channel.ExecuteOperationAsync(firstNumber, secondNumber, operation);
        }
        
        public int Add(int firstNumber, int secondNumber) {
            return base.Channel.Add(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber) {
            return base.Channel.AddAsync(firstNumber, secondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        kudvenkat.CalculatorService.GetLogOperationsResponse kudvenkat.CalculatorService.WebServiceCalculatorSoap.GetLogOperations(kudvenkat.CalculatorService.GetLogOperationsRequest request) {
            return base.Channel.GetLogOperations(request);
        }
        
        public kudvenkat.CalculatorService.ArrayOfString GetLogOperations() {
            kudvenkat.CalculatorService.GetLogOperationsRequest inValue = new kudvenkat.CalculatorService.GetLogOperationsRequest();
            inValue.Body = new kudvenkat.CalculatorService.GetLogOperationsRequestBody();
            kudvenkat.CalculatorService.GetLogOperationsResponse retVal = ((kudvenkat.CalculatorService.WebServiceCalculatorSoap)(this)).GetLogOperations(inValue);
            return retVal.Body.GetLogOperationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<kudvenkat.CalculatorService.GetLogOperationsResponse> kudvenkat.CalculatorService.WebServiceCalculatorSoap.GetLogOperationsAsync(kudvenkat.CalculatorService.GetLogOperationsRequest request) {
            return base.Channel.GetLogOperationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<kudvenkat.CalculatorService.GetLogOperationsResponse> GetLogOperationsAsync() {
            kudvenkat.CalculatorService.GetLogOperationsRequest inValue = new kudvenkat.CalculatorService.GetLogOperationsRequest();
            inValue.Body = new kudvenkat.CalculatorService.GetLogOperationsRequestBody();
            return ((kudvenkat.CalculatorService.WebServiceCalculatorSoap)(this)).GetLogOperationsAsync(inValue);
        }
    }
}
